name: HexagonWarrior
description: HexagonWarrior
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.11+1
  cupertino_icons: ^1.0.8
  webauthn: ^0.2.4
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  pin_code_fields: ^8.0.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.0
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  retrofit: ^4.0.1
  tuple: ^2.0.2
  throttling: ^1.0.0
  uuid: ^4.0.0
  logger: ^2.0.1
  url_launcher: ^6.1.8
  web_socket_channel: ^3.0.1

#  flutter_ethers: ^1.1.1
#  userop: ^0.3.0

  eth_sig_util: ^0.0.9
  freezed_annotation: ^2.4.1
  stream_channel: ^2.1.2
  web3dart: ^2.7.3

dependency_overrides:
  http: ^1.2.1
  analyzer: ^5.2.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  retrofit_generator: ^6.0.0
  json_serializable: ^6.7.1
  freezed: ^2.5.3
  web3dart_builders: ^0.1.2



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/contracts/
    - lib/api/
    - lib/api/requests/
    - lib/api/response/
