name: flutter_adaptive_scaffold_example
description: Multiple examples of the usage of the AdaptiveScaffold widget and its lower level widgets.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.11+1
  webauthn: ^0.2.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/potato.png
    - images/habanero.png
    - images/strawberry.png
    - images/plum.png
    - images/mushroom.png
    - images/avocado.png
